import React, { useState, useEffect } from 'react';
import { useApp } from '../../context/AppContext';
import { api } from '../../services/api';
import {
  QrCode,
  Phone,
  User,
  Image,
  Upload,
  Check,
  Save,
  RotateCcw,
  Sparkles,
  AlertCircle,
  Copy,
  Info
} from 'lucide-react';

export const PaymentConfigTab: React.FC = () => {
  const { yapeConfig, updateYapeConfig } = useApp();

  const [phone, setPhone] = useState(yapeConfig.phone || '925763903');
  const [phoneFormatted, setPhoneFormatted] = useState(yapeConfig.phoneFormatted || '+51 925 763 903');
  const [holder, setHolder] = useState(yapeConfig.holder || 'Super Administrador - SaaS Catálogo');
  const [qrUrl, setQrUrl] = useState(yapeConfig.qrUrl || '');
  const [instructions, setInstructions] = useState(
    yapeConfig.instructions ||
    'Abona el monto exacto por Yape o Plin. Luego ingresa el código de aprobación de 3 dígitos para verificación y activación inmediata de tu tienda.'
  );

  const [saving, setSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [uploadingQR, setUploadingQR] = useState(false);
  const [copiedPreview, setCopiedPreview] = useState(false);

  // Sincronizar cuando yapeConfig se cargue del backend
  useEffect(() => {
    if (yapeConfig) {
      setPhone(yapeConfig.phone || '925763903');
      setPhoneFormatted(yapeConfig.phoneFormatted || '+51 925 763 903');
      setHolder(yapeConfig.holder || 'Super Administrador - SaaS Catálogo');
      setQrUrl(yapeConfig.qrUrl || '');
      if (yapeConfig.instructions) {
        setInstructions(yapeConfig.instructions);
      }
    }
  }, [yapeConfig]);

  const cleanPhone = phone.replace(/\D/g, '') || '925763903';
  const autoGeneratedQR = `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://wa.me/51${cleanPhone}?text=Pago%20Yape%20SaaS%20Atalaya%20Store`;
  const activeQR = qrUrl.trim() || autoGeneratedQR;

  const handlePhoneChange = (val: string) => {
    const raw = val.replace(/\D/g, '').slice(0, 9);
    setPhone(raw);
    if (raw.length === 9) {
      setPhoneFormatted(`+51 ${raw.slice(0, 3)} ${raw.slice(3, 6)} ${raw.slice(6, 9)}`);
    } else {
      setPhoneFormatted(raw);
    }
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploadingQR(true);
    setSaveError(null);
    try {
      const res = await api.uploadImage(file, 'banners');
      if (res && res.url) {
        setQrUrl(res.url);
      }
    } catch (err: any) {
      setSaveError(err.message || 'Error al subir la imagen del QR.');
    } finally {
      setUploadingQR(false);
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setSaveError(null);
    setSaveSuccess(false);

    try {
      await updateYapeConfig({
        phone: cleanPhone,
        phoneFormatted: phoneFormatted.trim() || `+51 ${cleanPhone}`,
        holder: holder.trim() || 'Super Administrador - SaaS Catálogo',
        qrUrl: qrUrl.trim(),
        instructions: instructions.trim()
      });
      setSaveSuccess(true);
      setTimeout(() => setSaveSuccess(false), 3500);
    } catch (err: any) {
      setSaveError(err.message || 'Error al guardar la configuración de Yape.');
    } finally {
      setSaving(false);
    }
  };

  const handleResetDefaults = () => {
    if (window.confirm('¿Deseas restablecer los valores de cobro a los predeterminados del sistema?')) {
      setPhone('925763903');
      setPhoneFormatted('+51 925 763 903');
      setHolder('Super Administrador - SaaS Catálogo');
      setQrUrl('');
      setInstructions(
        'Abona el monto exacto por Yape o Plin. Luego ingresa el código de aprobación de 3 dígitos para verificación y activación inmediata de tu tienda.'
      );
    }
  };

  const handleCopyPreview = () => {
    navigator.clipboard.writeText(cleanPhone);
    setCopiedPreview(true);
    setTimeout(() => setCopiedPreview(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-purple-900 via-indigo-900 to-neutral-900 rounded-3xl p-6 sm:p-8 text-white shadow-xl relative overflow-hidden">
        <div className="absolute right-0 top-0 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="relative z-10 max-w-2xl space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-purple-200 text-xs font-black uppercase tracking-wider border border-white/10">
            <QrCode className="w-3.5 h-3.5 text-purple-300" />
            <span>Cobros SaaS & Pasarela Yape</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black tracking-tight">
            Configuración de QR & Cuenta Yape / Plin
          </h2>
          <p className="text-xs sm:text-sm text-purple-200/90 leading-relaxed">
            Personaliza el número de teléfono, la imagen del código QR y los datos del titular que visualizarán todos los comerciantes al adquirir o renovar sus planes de suscripción.
          </p>
        </div>
      </div>

      {saveSuccess && (
        <div className="flex items-center gap-3 p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-900 text-xs font-bold animate-in fade-in shadow-xs">
          <div className="w-8 h-8 rounded-xl bg-emerald-500 text-white flex items-center justify-center shrink-0">
            <Check className="w-5 h-5" />
          </div>
          <div>
            <p className="font-extrabold text-sm">¡Configuración guardada correctamente!</p>
            <p className="text-emerald-700 font-normal">Los datos del QR y número de Yape se han sincronizado para todos los comercios.</p>
          </div>
        </div>
      )}

      {saveError && (
        <div className="flex items-center gap-3 p-4 rounded-2xl bg-rose-50 border border-rose-200 text-rose-900 text-xs font-bold animate-in fade-in">
          <AlertCircle className="w-5 h-5 text-rose-600 shrink-0" />
          <span>{saveError}</span>
        </div>
      )}

      {/* Main Form & Live Preview Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Form Column */}
        <div className="lg:col-span-7 bg-white rounded-3xl border border-neutral-200 p-6 sm:p-7 shadow-xs space-y-5">
          <div className="flex items-center justify-between pb-3 border-b border-neutral-100">
            <div className="flex items-center gap-2">
              <span className="p-1.5 rounded-lg bg-purple-100 text-purple-700">
                <Sparkles className="w-4 h-4" />
              </span>
              <h3 className="font-black text-neutral-900 text-sm">
                Datos de Cobro Oficial
              </h3>
            </div>
            <button
              type="button"
              onClick={handleResetDefaults}
              className="text-xs font-semibold text-neutral-500 hover:text-purple-700 flex items-center gap-1 cursor-pointer transition-colors"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Restablecer</span>
            </button>
          </div>

          <form onSubmit={handleSave} className="space-y-4 text-xs">
            {/* Teléfono Yape */}
            <div>
              <label className="block font-bold text-neutral-700 mb-1">
                Número Yape / Plin (9 dígitos) <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400 font-bold">
                  +51
                </span>
                <input
                  type="tel"
                  maxLength={9}
                  required
                  placeholder="925763903"
                  value={phone}
                  onChange={e => handlePhoneChange(e.target.value)}
                  className="w-full pl-12 pr-3 py-2.5 rounded-xl border border-neutral-300 font-mono font-bold text-sm text-neutral-900 focus:outline-hidden focus:ring-2 focus:ring-purple-600 focus:border-purple-600 bg-white"
                />
              </div>
              <p className="text-[11px] text-neutral-400 mt-1">
                Número al cual los comerciantes transferirán el costo de su suscripción.
              </p>
            </div>

            {/* Formato Visible del Teléfono */}
            <div>
              <label className="block font-bold text-neutral-700 mb-1">
                Texto Formateado Visible <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <Phone className="w-4 h-4 text-neutral-400 absolute left-3 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  required
                  placeholder="+51 925 763 903"
                  value={phoneFormatted}
                  onChange={e => setPhoneFormatted(e.target.value)}
                  className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-neutral-300 font-mono text-xs text-neutral-900 focus:outline-hidden focus:ring-2 focus:ring-purple-600 bg-white"
                />
              </div>
              <p className="text-[11px] text-neutral-400 mt-1">
                Cómo se mostrará impreso en la interfaz (ej. +51 925 763 903).
              </p>
            </div>

            {/* Titular de la Cuenta */}
            <div>
              <label className="block font-bold text-neutral-700 mb-1">
                Nombre del Titular de la Cuenta <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <User className="w-4 h-4 text-neutral-400 absolute left-3 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  required
                  placeholder="Super Administrador - SaaS Catálogo"
                  value={holder}
                  onChange={e => setHolder(e.target.value)}
                  className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-neutral-300 text-xs font-semibold text-neutral-900 focus:outline-hidden focus:ring-2 focus:ring-purple-600 bg-white"
                />
              </div>
              <p className="text-[11px] text-neutral-400 mt-1">
                Nombre que figura registrado en la app de Yape/Plin para que el comerciante verifique la titularidad.
              </p>
            </div>

            {/* Configuración del QR */}
            <div className="p-4 rounded-2xl bg-neutral-50 border border-neutral-200 space-y-3">
              <div className="flex items-center justify-between">
                <label className="font-extrabold text-neutral-800 text-xs flex items-center gap-1.5">
                  <Image className="w-4 h-4 text-purple-600" />
                  <span>Código QR de Pago</span>
                </label>
                {qrUrl ? (
                  <span className="px-2 py-0.5 rounded-md text-[10px] font-extrabold bg-purple-100 text-purple-800">
                    Imagen Personalizada
                  </span>
                ) : (
                  <span className="px-2 py-0.5 rounded-md text-[10px] font-extrabold bg-emerald-100 text-emerald-800">
                    Auto-generado desde Número
                  </span>
                )}
              </div>

              {/* Subir archivo de imagen propio */}
              <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 pt-1">
                <label className="flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-dashed border-purple-300 hover:border-purple-600 bg-white hover:bg-purple-50/50 text-purple-900 font-bold text-xs cursor-pointer transition-all shadow-xs">
                  <Upload className="w-4 h-4 text-purple-600" />
                  <span>{uploadingQR ? 'Subiendo imagen...' : 'Subir Imagen de QR (PNG/JPG)'}</span>
                  <input
                    type="file"
                    accept="image/*"
                    disabled={uploadingQR}
                    onChange={handleFileUpload}
                    className="hidden"
                  />
                </label>

                {qrUrl && (
                  <button
                    type="button"
                    onClick={() => setQrUrl('')}
                    className="text-[11px] font-bold text-rose-600 hover:underline cursor-pointer py-1 self-center"
                  >
                    Quitar imagen y usar QR automático
                  </button>
                )}
              </div>

              {/* O bien ingresar URL directa */}
              <div>
                <label className="block text-[11px] font-semibold text-neutral-500 mb-1">
                  O ingresa URL directa de la imagen del QR (opcional):
                </label>
                <input
                  type="url"
                  placeholder="https://.../mi_qr_yape.png (dejar vacío para auto-generar)"
                  value={qrUrl}
                  onChange={e => setQrUrl(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl border border-neutral-300 text-xs font-mono text-neutral-700 bg-white focus:outline-hidden focus:ring-2 focus:ring-purple-600"
                />
              </div>
            </div>

            {/* Instrucciones de Pago */}
            <div>
              <label className="block font-bold text-neutral-700 mb-1">
                Instrucciones Adicionales para el Comerciante
              </label>
              <textarea
                rows={2}
                value={instructions}
                onChange={e => setInstructions(e.target.value)}
                placeholder="Abona el monto exacto por Yape..."
                className="w-full px-3 py-2 rounded-xl border border-neutral-300 text-xs text-neutral-800 bg-white focus:outline-hidden focus:ring-2 focus:ring-purple-600 resize-none"
              />
            </div>

            {/* Botón Guardar */}
            <div className="pt-3 border-t border-neutral-100 flex items-center justify-end gap-3">
              <button
                type="submit"
                disabled={saving || uploadingQR}
                className="px-6 py-3 rounded-2xl bg-gradient-to-r from-purple-700 to-indigo-700 hover:from-purple-800 hover:to-indigo-800 text-white font-black text-xs shadow-lg shadow-purple-600/20 flex items-center gap-2 cursor-pointer transition-all active:scale-[0.99] disabled:opacity-50"
              >
                <Save className="w-4 h-4" />
                <span>{saving ? 'Guardando Cambios...' : 'Guardar Configuración de Cobro'}</span>
              </button>
            </div>
          </form>
        </div>

        {/* Live Preview Column */}
        <div className="lg:col-span-5 space-y-4">
          <div className="flex items-center gap-2 px-1">
            <span className="p-1 rounded-md bg-purple-100 text-purple-700">
              <QrCode className="w-4 h-4" />
            </span>
            <h3 className="font-black text-neutral-900 text-sm">
              Vista Previa en Tiempo Real
            </h3>
          </div>

          {/* Tarjeta idéntica a la que ve el comerciante */}
          <div className="rounded-3xl border-2 border-purple-200 bg-gradient-to-b from-purple-50/70 to-white p-5 space-y-4 shadow-sm">
            <div className="flex items-center justify-between pb-3 border-b border-purple-100">
              <div>
                <span className="text-[10px] font-black uppercase text-purple-700 tracking-wider">
                  Total a transferir
                </span>
                <div className="flex items-baseline gap-1 mt-0.5">
                  <span className="text-2xl font-black text-neutral-900">S/ 25.00</span>
                  <span className="text-[10px] text-neutral-500 font-medium">PEN</span>
                </div>
              </div>
              <div className="px-3 py-1.5 rounded-2xl bg-purple-600 text-white text-[11px] font-black shadow-xs">
                Yape / Plin Oficial
              </div>
            </div>

            <div className="flex flex-col items-center justify-center p-3.5 rounded-2xl bg-gradient-to-br from-purple-900 via-indigo-900 to-purple-950 text-white text-center shadow-md">
              <div className="w-40 h-40 bg-white p-2 rounded-2xl shadow-inner flex items-center justify-center overflow-hidden">
                <img
                  src={activeQR}
                  alt="QR Yape Pago"
                  className="w-full h-full object-contain"
                  onError={(e) => {
                    (e.target as HTMLImageElement).src = autoGeneratedQR;
                  }}
                />
              </div>
              <span className="text-[11px] font-bold text-purple-200 mt-2.5 flex items-center gap-1.5">
                <QrCode className="w-3.5 h-3.5" />
                <span>Escanea con Yape o Plin</span>
              </span>
            </div>

            {/* Número y Titular Preview */}
            <div className="space-y-3 bg-white rounded-2xl p-4 border border-neutral-200 text-xs">
              <div>
                <span className="text-[10px] font-bold text-neutral-400 block uppercase">
                  Número Yape / Plin
                </span>
                <div className="flex items-center gap-2 mt-0.5">
                  <span className="text-lg font-mono font-black text-purple-900 tracking-wider">
                    {phoneFormatted || phone}
                  </span>
                  <button
                    type="button"
                    onClick={handleCopyPreview}
                    className="px-2.5 py-1 rounded-lg bg-neutral-100 hover:bg-neutral-200 text-neutral-700 font-bold text-[10px] flex items-center gap-1 transition-colors cursor-pointer"
                  >
                    {copiedPreview ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
                    <span>{copiedPreview ? 'Copiado' : 'Copiar'}</span>
                  </button>
                </div>
              </div>

              <div>
                <span className="text-[10px] font-bold text-neutral-400 block uppercase">
                  Titular de Cuenta
                </span>
                <span className="font-bold text-neutral-800 text-xs block">
                  {holder}
                </span>
              </div>

              <div className="p-2.5 rounded-xl bg-purple-50 border border-purple-200/80 text-[11px] text-purple-950 font-medium leading-relaxed">
                {instructions}
              </div>
            </div>
          </div>

          <div className="p-4 rounded-2xl bg-indigo-50/70 border border-indigo-200/70 text-indigo-900 text-xs space-y-1">
            <div className="flex items-center gap-1.5 font-bold text-indigo-950">
              <Info className="w-4 h-4 text-indigo-600 shrink-0" />
              <span>¿Cómo funciona la activación?</span>
            </div>
            <p className="text-[11px] text-indigo-800/90 leading-relaxed">
              Cuando el comerciante escanea este QR o yapea a este número, ingresa su código de 3 dígitos y el sistema valida la transacción automáticamente.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
